### ISSUE TITLE
Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by Jxells** [zhuweiyou/chatgpt-api#27]
SyntaxError: Unexpected non-whitespace character after JSON at position 4
    at JSON.parse (<anonymous>)
    at onMessage (file:///home/jxell/chatgpt-api/node_modules/chatgpt/build/index.js:622:47)
    at file:///home/jxell/chatgpt-api/node_modules/chatgpt/build/index.js:62:7
    at parseEventStreamLine (file:///home/jxell/chatgpt-api/node_modules/eventsource-parser/dist/index.js:73:9)
    at Object.feed (file:///home/jxell/chatgpt-api/node_modules/eventsource-parser/dist/index.js:61:7)
    at feed (file:///home/jxell/chatgpt-api/node_modules/chatgpt/build/index.js:84:12)
    at fetchSSE (file:///home/jxell/chatgpt-api/node_modules/chatgpt/build/index.js:100:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by zhuweiyou** [comment]
信息太少,不好判断

**Comment by Guosen-Wu** [comment]
![QQ截图20230506231244](https://user-images.githubusercontent.com/98222448/236632625-3ca46009-8968-4d82-bab6-f1a5b616966c.png)
报错的地方改这样就可以忽略错误得到正确结果
